import type { Food, MealType } from '../types';

export const FOODS_BY_MEAL: Record<MealType, Food[]> = {
  breakfast: [
    { id: 'ham_cheese_toast', name: '햄치즈 토스트', subcategory: 'main', nutrition: { calories: 430, sugar: 6, saturatedFat: 7, transFat: 0.5 } },
    { id: 'tuna_kimbap', name: '참치 김밥 한 줄', subcategory: 'main', nutrition: { calories: 500, sugar: 6, saturatedFat: 2.5, transFat: 0.1 } },
    { id: 'cornflakes_milk', name: '콘푸라이트 + 우유', subcategory: 'main', nutrition: { calories: 240, sugar: 16, saturatedFat: 2, transFat: 0 } },
    { id: 'egg_kimchi_rice', name: '계란후라이 + 김치볶음밥', subcategory: 'main', nutrition: { calories: 700, sugar: 8, saturatedFat: 5, transFat: 0.3 } },
    { id: 'blueberry_smoothie', name: '블루베리 요거트 스무디', subcategory: 'main', nutrition: { calories: 380, sugar: 32, saturatedFat: 3, transFat: 0 } },
    { id: 'egg_mayo_sandwich', name: '에그마요 샌드위치', subcategory: 'main', nutrition: { calories: 500, sugar: 6, saturatedFat: 6, transFat: 0.4 } },
    { id: 'chicken_tender_salad', name: '치킨텐더 샐러드', subcategory: 'main', nutrition: { calories: 420, sugar: 6, saturatedFat: 4, transFat: 0.3 } },
    { id: 'banana', name: '바나나 1개', subcategory: 'side', nutrition: { calories: 100, sugar: 13, saturatedFat: 0.1, transFat: 0 } },
  ],
  lunch: [
    { id: 'chicken_mayo_rice', name: '치킨마요 덮밥', subcategory: 'main', nutrition: { calories: 720, sugar: 9, saturatedFat: 9, transFat: 0.5 } },
    { id: 'pork_rice', name: '제육덮밥', subcategory: 'main', nutrition: { calories: 780, sugar: 12, saturatedFat: 4, transFat: 0.3 } },
    { id: 'pork_cutlet', name: '돈까스', subcategory: 'main', nutrition: { calories: 850, sugar: 11, saturatedFat: 8, transFat: 0.8 } },
    { id: 'tteok_sun_twi', name: '떡순튀', subcategory: 'main', nutrition: { calories: 950, sugar: 28, saturatedFat: 7, transFat: 0.7 } },
    { id: 'army_stew', name: '부대찌개 + 라면사리', subcategory: 'main', nutrition: { calories: 900, sugar: 7, saturatedFat: 10, transFat: 1.0 } },
    { id: 'jeonju_bibimbap', name: '전주비빔밥', subcategory: 'main', nutrition: { calories: 650, sugar: 10, saturatedFat: 3, transFat: 0.2 } },
    { id: 'malatang', name: '마라탕', subcategory: 'main', nutrition: { calories: 850, sugar: 6, saturatedFat: 11, transFat: 0.6 } },
    { id: 'jajang_tangsuyuk', name: '짜장면 + 탕수육(소)', subcategory: 'main', nutrition: { calories: 1400, sugar: 24, saturatedFat: 13, transFat: 1.5 } },
    { id: 'sundae_gukbap', name: '순대국밥', subcategory: 'main', nutrition: { calories: 800, sugar: 3, saturatedFat: 9, transFat: 0.5 } },
    { id: 'wagyu_burger', name: '한우불고기버거 세트', subcategory: 'main', nutrition: { calories: 1030, sugar: 49, saturatedFat: 12, transFat: 1.0 } },
    { id: 'clam_noodle', name: '바지락 칼국수', subcategory: 'main', nutrition: { calories: 680, sugar: 4, saturatedFat: 1.5, transFat: 0 } },
    { id: 'shin_ramyeon', name: '신라면', subcategory: 'main', nutrition: { calories: 500, sugar: 4, saturatedFat: 8, transFat: 0 } },
    { id: 'soda_can', name: '탄산음료 1캔', subcategory: 'side', nutrition: { calories: 140, sugar: 35, saturatedFat: 0, transFat: 0 } },
  ],
  snack: [
    { id: 'injeolmi_bingsu', name: '인절미 빙수', subcategory: 'main', nutrition: { calories: 510, sugar: 47, saturatedFat: 10, transFat: 0 } },
    { id: 'choco_cake', name: '초코 조각케이크', subcategory: 'main', nutrition: { calories: 545, sugar: 38, saturatedFat: 14, transFat: 0.6 } },
    { id: 'salt_bread', name: '소금빵', subcategory: 'main', nutrition: { calories: 305, sugar: 3, saturatedFat: 6, transFat: 0.3 } },
    { id: 'two_chok', name: '두쫀크 50g', subcategory: 'main', nutrition: { calories: 250, sugar: 30, saturatedFat: 10, transFat: 0.1 } },
    { id: 'honey_butter_chips', name: '허니버터칩 1봉지', subcategory: 'main', nutrition: { calories: 360, sugar: 6, saturatedFat: 4.5, transFat: 0 } },
    { id: 'hotteok', name: '호떡', subcategory: 'main', nutrition: { calories: 230, sugar: 17, saturatedFat: 3, transFat: 0.2 } },
    { id: 'cup_fruit', name: '컵과일', subcategory: 'main', nutrition: { calories: 120, sugar: 20, saturatedFat: 0, transFat: 0 } },
    { id: 'iced_tea', name: '아이스티 레귤러', subcategory: 'side', nutrition: { calories: 90, sugar: 21, saturatedFat: 0, transFat: 0 } },
    { id: 'vanilla_latte', name: '바닐라라떼 레귤러', subcategory: 'side', nutrition: { calories: 180, sugar: 22, saturatedFat: 5, transFat: 0.3 } },
    { id: 'americano', name: '아메리카노', subcategory: 'side', nutrition: { calories: 10, sugar: 0, saturatedFat: 0, transFat: 0 } },
    { id: 'green_tea_latte', name: '그린티라떼', subcategory: 'side', nutrition: { calories: 205, sugar: 20, saturatedFat: 5, transFat: 0.2 } },
    { id: 'cola_can', name: '콜라 1캔(355mL)', subcategory: 'side', nutrition: { calories: 140, sugar: 35, saturatedFat: 0, transFat: 0 } },
    { id: 'banana_milk', name: '바나나우유', subcategory: 'side', nutrition: { calories: 208, sugar: 27, saturatedFat: 4.5, transFat: 0 } },
    { id: 'oreo_mcflurry', name: '오레오 맥플러리', subcategory: 'side', nutrition: { calories: 330, sugar: 30, saturatedFat: 6, transFat: 0.3 } },
  ],
  dinner: [
    { id: 'yeoptteok_set', name: '엽떡 로제떡볶이 + 주먹밥 + 주스', subcategory: 'main', nutrition: { calories: 1850, sugar: 65, saturatedFat: 24, transFat: 1.5 } },
    { id: 'honey_combo', name: '허니콤보 + 콜라 500mL', subcategory: 'main', nutrition: { calories: 1400, sugar: 70, saturatedFat: 14, transFat: 1.2 } },
    { id: 'steak_pasta', name: '채끝 스테이크 300g + 크림파스타', subcategory: 'main', nutrition: { calories: 1650, sugar: 11, saturatedFat: 28, transFat: 2.0 } },
    { id: 'beef_intestine', name: '소곱창구이 + 볶음밥', subcategory: 'main', nutrition: { calories: 1500, sugar: 8, saturatedFat: 25, transFat: 2.3 } },
    { id: 'sushi_soba', name: '모듬초밥 + 냉모밀', subcategory: 'main', nutrition: { calories: 980, sugar: 18, saturatedFat: 4, transFat: 0.3 } },
    { id: 'samgyeopsal_naengmyeon', name: '삼겹살 1인분 + 냉면', subcategory: 'main', nutrition: { calories: 1150, sugar: 16, saturatedFat: 18, transFat: 0.8 } },
    { id: 'jokbal_makguksu', name: '족발 + 막국수', subcategory: 'main', nutrition: { calories: 1400, sugar: 24, saturatedFat: 17, transFat: 1.0 } },
  ],
};
